import { Head, Link, router } from "@inertiajs/react";
import { Building2, ChevronDown, Pencil, Plus, Store as StoreIcon, UserRound } from "lucide-react";
import PublicLayout from "../../layouts/PublicLayout";

type SellerStore = { id:number; name:string; slug:string; status:string; logo_url?:string|null; business_name:string; role:string; is_primary_owner:boolean };
type Props = { stores:SellerStore[]; activeStoreId:number|null };

export default function Dashboard({stores,activeStoreId}:Props){
 const active=stores.find(store=>store.id===activeStoreId) ?? stores[0];
 return <PublicLayout><Head title="Seller Dashboard | Dubai Lanka"/><main className="bg-surface-subtle py-8 sm:py-10"><div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
  <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold text-brand-secondary">SELLER DASHBOARD</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-text-primary">Manage your stores</h1><p className="mt-2 text-sm text-text-muted">Switch between only the stores your account can access.</p></div><Link href="/seller/start" className="inline-flex cursor-pointer items-center gap-2 rounded-lg bg-brand-secondary px-4 py-2.5 text-sm font-bold text-white hover:bg-brand-secondary-hover"><Plus size={17}/> Business & Stores</Link></div>
  {stores.length===0?<div className="mt-8 rounded-xl border border-border bg-surface p-8 text-center"><StoreIcon className="mx-auto size-10 text-text-muted"/><h2 className="mt-4 text-lg font-bold text-text-primary">No store access yet</h2><p className="mt-2 text-sm text-text-muted">Create your first business and store to start the seller workspace.</p><Link href="/seller/start" className="mt-5 inline-flex cursor-pointer items-center rounded-lg bg-brand-secondary px-4 py-2.5 text-sm font-bold text-white">Start Selling</Link></div>:
  <><section className="mt-8 rounded-xl border border-border bg-surface p-5 sm:p-6"><label htmlFor="store-switcher" className="text-xs font-bold uppercase tracking-wide text-text-muted">Working Store</label><div className="relative mt-2 max-w-md"><select id="store-switcher" value={active?.id ?? ""} onChange={e=>router.get('/seller/dashboard',{store:Number(e.target.value)},{preserveState:true,replace:true})} className="w-full cursor-pointer appearance-none rounded-lg border border-border bg-surface px-4 py-3 pr-10 text-sm font-bold text-text-primary outline-none focus:border-brand-secondary"><>{stores.map(store=><option key={store.id} value={store.id}>{store.name} — {store.business_name}</option>)}</></select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 size-4 -translate-y-1/2 text-text-muted"/></div></section>
  {active&&<section className="mt-6 rounded-xl border border-border bg-surface p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-start gap-4">{active.logo_url?<img src={active.logo_url} alt="" className="size-14 rounded-lg border border-border object-cover"/>:<div className="flex size-14 items-center justify-center rounded-lg bg-brand-secondary-soft text-brand-secondary"><StoreIcon size={24}/></div>}<div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-bold text-text-primary">{active.name}</h2><span className="rounded-full bg-warning-soft px-2.5 py-1 text-xs font-bold capitalize text-warning">{active.status.replace('_',' ')}</span></div><p className="mt-1 text-sm text-text-muted">{active.business_name} · /{active.slug}</p><div className="mt-3 flex flex-wrap gap-2"><span className="inline-flex items-center gap-1 rounded-full bg-brand-secondary-soft px-2.5 py-1 text-xs font-bold capitalize text-brand-secondary"><UserRound size={13}/>{active.role}</span>{active.is_primary_owner&&<span className="rounded-full bg-success-soft px-2.5 py-1 text-xs font-bold text-success">Primary Owner</span>}</div></div></div><Link href={`/seller/stores/${active.id}/edit`} className="inline-flex cursor-pointer items-center gap-2 rounded-lg border border-border px-4 py-2.5 text-sm font-bold text-text-primary hover:border-brand-secondary hover:text-brand-secondary"><Pencil size={16}/> Edit Draft</Link></div></section>}
  <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><div className="rounded-xl border border-border bg-surface p-5"><Building2 className="size-5 text-brand-secondary"/><h3 className="mt-3 font-bold text-text-primary">Store workspace ready</h3><p className="mt-2 text-sm leading-6 text-text-muted">Products, inquiries, orders and reports will be added in their planned milestones.</p></div><div className="rounded-xl border border-border bg-surface p-5"><UserRound className="size-5 text-brand-secondary"/><h3 className="mt-3 font-bold text-text-primary">Membership foundation</h3><p className="mt-2 text-sm leading-6 text-text-muted">This account is scoped to this store. Detailed Manager and Staff permissions come in Milestone 04.</p></div></section></>}
 </div></main></PublicLayout>;
}
