import { Head, Link, usePage } from "@inertiajs/react";
import { ArrowRight, Building2, CheckCircle2, Pencil, Plus, Store, UserRound } from "lucide-react";
import PublicLayout from "../../layouts/PublicLayout";

type Business = { id:number; type:"personal_business"|"registered_company"; legal_name:string; trading_name?:string|null; country_code:string; status:string };
type StoreDraft = { id:number; business_entity_id:number; name:string; slug:string; status:string; logo_path?:string|null; updated_at:string };
type PageProps = { businesses:Business[]; stores:StoreDraft[]; pendingHandover?:boolean; flash?:{success?:string} };

export default function Start({businesses,stores,pendingHandover=false}:PageProps){
 const {props}=usePage<PageProps>(); const success=props.flash?.success;
 const storeCount=(businessId:number)=>stores.filter(s=>s.business_entity_id===businessId).length;
 const drafts=stores.filter(s=>s.status==="draft");
 return <PublicLayout><Head title="Start Selling | Dubai Lanka"/><main className="bg-surface-subtle py-10 sm:py-14"><div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">
 {pendingHandover&&<div className="mb-6 rounded-lg border border-brand-secondary/20 bg-brand-secondary-soft p-4 text-sm text-brand-secondary"><strong>Dubai Lanka handed this seller setup to you.</strong><p className="mt-1">Create your Business Entity below, then add your Store when you are ready.</p></div>}
 {success&&<div className="mb-6 flex items-start gap-3 rounded-lg border border-success/20 bg-success-soft p-4 text-sm text-success"><CheckCircle2 className="mt-0.5 size-5 shrink-0"/><span>{success}</span></div>}
 <div className="flex flex-wrap items-start justify-between gap-4"><div className="max-w-2xl"><p className="text-sm font-bold text-brand-secondary">SELL ON DUBAI LANKA</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-text-primary sm:text-4xl">Start your seller journey</h1><p className="mt-4 text-base leading-7 text-text-secondary">Create your business identity, then add one or more stores under it. Store package limits will be connected in a later milestone.</p></div>{stores.length>0&&<Link href="/seller/dashboard" className="inline-flex cursor-pointer items-center gap-2 rounded-lg bg-brand-secondary px-4 py-2.5 text-sm font-bold text-white hover:bg-brand-secondary-hover"><Store size={16}/> Seller Dashboard</Link>}</div>
 {businesses.length>0&&<section className="mt-8 rounded-xl border border-border bg-surface p-4 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold text-text-primary">Your businesses</h2><p className="mt-1 text-sm text-text-muted">Manage your business identities and create one or more stores under each business.</p></div><span className="rounded-full bg-brand-secondary-soft px-3 py-1 text-xs font-bold text-brand-secondary">{businesses.length} {businesses.length===1?"business":"businesses"}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{businesses.map(b=>{const count=storeCount(b.id);return <div key={b.id} className="rounded-lg border border-border p-4 transition hover:border-brand-secondary/50"><div className="flex items-start gap-3"><div className={`flex size-10 shrink-0 items-center justify-center rounded-lg ${b.type==="registered_company"?"bg-brand-primary-soft text-warning":"bg-brand-secondary-soft text-brand-secondary"}`}>{b.type==="registered_company"?<Building2 size={19}/>:<UserRound size={19}/>}</div><div className="min-w-0 flex-1"><p className="text-[11px] font-bold uppercase tracking-wide text-text-muted">{b.type==="registered_company"?"Registered Company":"Personal Business"}</p><p className="mt-0.5 truncate font-bold text-text-primary">{b.trading_name||b.legal_name}</p>{b.trading_name&&<p className="mt-0.5 truncate text-xs text-text-muted">{b.legal_name}</p>}</div></div><div className="mt-4 flex flex-wrap items-center gap-x-3 gap-y-2"><span className="text-xs font-semibold text-success">Active</span><span className="h-3 w-px bg-border"/><span className="text-xs font-semibold text-text-muted">{count} {count===1?"store":"stores"}</span><Link href={`/seller/stores/create?business=${b.id}`} className="ml-auto inline-flex min-h-10 cursor-pointer items-center justify-center gap-1.5 rounded-lg bg-brand-secondary px-3 py-2 text-sm font-bold text-white hover:bg-brand-secondary-hover"><Plus size={15}/> Create Store</Link></div></div>})}</div></section>}
 {drafts.length>0&&<section className="mt-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-bold text-text-primary">Your store drafts</h2><p className="mt-1 text-sm text-text-muted">Drafts are private and can be edited anytime.</p></div><span className="rounded-full bg-warning-soft px-3 py-1 text-xs font-bold text-warning">{drafts.length} {drafts.length===1?"draft":"drafts"}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{drafts.map(s=><Link key={s.id} href={`/seller/stores/${s.id}/edit`} className="group cursor-pointer rounded-xl border border-border bg-surface p-4 transition hover:border-brand-secondary"><div className="flex items-start gap-3"><div className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-brand-secondary-soft text-brand-secondary"><Store size={20}/></div><div className="min-w-0 flex-1"><p className="truncate font-bold text-text-primary">{s.name}</p><p className="mt-1 truncate text-xs text-text-muted">/{s.slug}</p></div></div><div className="mt-4 flex items-center justify-between"><span className="rounded-full bg-warning-soft px-2.5 py-1 text-xs font-bold text-warning">Draft</span><span className="inline-flex items-center gap-1 text-sm font-bold text-brand-secondary">Edit <Pencil size={14}/></span></div></Link>)}</div></section>}
 <section className="mt-8 rounded-xl border border-border bg-surface p-4 sm:p-6"><h2 className="text-xl font-bold text-text-primary">{businesses.length?"Add another business":"How are you selling?"}</h2><p className="mt-1 text-sm text-text-muted">{businesses.length?"Create another business identity only when you need a separate business.":"Choose the business type that best matches how you sell."}</p><div className="mt-4 grid gap-3 md:grid-cols-2"><Link href="/seller/businesses/create?type=personal_business" className="group flex cursor-pointer items-center gap-3 rounded-lg border border-border p-4 transition hover:border-brand-secondary"><div className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-brand-secondary-soft text-brand-secondary"><UserRound size={20}/></div><div className="min-w-0 flex-1"><h3 className="font-bold text-text-primary">Personal Business</h3><p className="mt-1 text-xs leading-5 text-text-secondary">For an individual or trading business without a registered company.</p></div><ArrowRight size={18} className="shrink-0 text-brand-secondary transition-transform group-hover:translate-x-1"/></Link><Link href="/seller/businesses/create?type=registered_company" className="group flex cursor-pointer items-center gap-3 rounded-lg border border-border p-4 transition hover:border-brand-secondary"><div className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-brand-primary-soft text-warning"><Building2 size={20}/></div><div className="min-w-0 flex-1"><h3 className="font-bold text-text-primary">Registered Company</h3><p className="mt-1 text-xs leading-5 text-text-secondary">For a legally registered company operating in the UAE or Sri Lanka.</p></div><ArrowRight size={18} className="shrink-0 text-brand-secondary transition-transform group-hover:translate-x-1"/></Link></div></section>
 </div></main></PublicLayout>;
}
