<?php
namespace App\Http\Controllers\Seller;
use App\Http\Controllers\Controller;use App\Models\Store;use App\Models\StoreChangeRequest;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Inertia\Inertia;use Inertia\Response;
class DashboardController extends Controller{
 public function __invoke(Request $request):Response{$stores=$this->stores($request);$requested=$request->integer('store')?:$request->session()->get('seller_active_store_id');$active=$stores->contains('id',$requested)?$requested:($stores->first()['id']??null);if($active)$request->session()->put('seller_active_store_id',$active);return Inertia::render('Seller/Dashboard',['stores'=>$stores,'activeStoreId'=>$active]);}
 public function activeStore(Request $request):RedirectResponse{$data=$request->validate(['store_id'=>['required','integer']]);abort_unless($request->user()->stores()->whereKey($data['store_id'])->exists(),403);$request->session()->put('seller_active_store_id',$data['store_id']);return back();}
 public function show(Request $request,Store $store):Response{abort_unless($request->user()->stores()->whereKey($store->id)->exists(),403);$request->session()->put('seller_active_store_id',$store->id);$store->load(['businessEntity:id,legal_name,trading_name','statusHistories.actor:id,name,email','changeRequests'=>fn($q)=>$q->whereIn('status',[StoreChangeRequest::STATUS_PENDING,StoreChangeRequest::STATUS_UNDER_REVIEW,StoreChangeRequest::STATUS_NEEDS_CHANGES])->latest()]);$stores=$this->stores($request);return Inertia::render('Seller/Store/Manage',['store'=>$store,'stores'=>$stores,'activeStoreId'=>$store->id,'canResubmit'=>$store->status===Store::STATUS_DRAFT||($store->status===Store::STATUS_NEEDS_CHANGES&&$store->review_changes_saved_at!==null)]);}
 private function stores(Request $request){return $request->user()->stores()->with(['businessEntity:id,legal_name,trading_name','statusHistories'=>fn($q)=>$q->limit(1),'changeRequests'=>fn($q)=>$q->whereIn('status',[StoreChangeRequest::STATUS_PENDING,StoreChangeRequest::STATUS_UNDER_REVIEW,StoreChangeRequest::STATUS_NEEDS_CHANGES])->limit(1)])->orderBy('stores.name')->get(['stores.id','stores.business_entity_id','stores.name','stores.slug','stores.status','stores.logo_path','stores.review_changes_saved_at'])->map(function(Store $store){$change=$store->changeRequests->first();return ['id'=>$store->id,'name'=>$store->name,'slug'=>$store->slug,'status'=>$store->status,'logo_url'=>$store->logo_url,'business_name'=>$store->businessEntity->trading_name?:$store->businessEntity->legal_name,'role'=>$store->pivot->role,'is_primary_owner'=>(bool)$store->pivot->is_primary_owner,'status_note'=>$store->statusHistories->first()?->note,'change_status'=>$change?->status,'change_note'=>$change?->admin_note,'can_resubmit'=>$store->status===Store::STATUS_DRAFT||($store->status===Store::STATUS_NEEDS_CHANGES&&$store->review_changes_saved_at!==null)];})->values();}
}
