<?php
namespace App\Http\Controllers\Admin;
use App\Actions\Store\ChangeStoreStatus; use App\Http\Controllers\Controller; use App\Models\Store; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Inertia\Inertia; use Inertia\Response;
class StoreModerationController extends Controller {
 public function index():Response{$stores=Store::with('businessEntity:id,legal_name,trading_name')->whereIn('status',[Store::STATUS_PENDING,Store::STATUS_UNDER_REVIEW,Store::STATUS_NEEDS_CHANGES,Store::STATUS_APPROVED,Store::STATUS_REJECTED,Store::STATUS_SUSPENDED])->latest('updated_at')->get()->map(fn($s)=>['id'=>$s->id,'name'=>$s->name,'slug'=>$s->slug,'status'=>$s->status,'business_name'=>$s->businessEntity->trading_name?:$s->businessEntity->legal_name,'country_code'=>$s->country_code,'updated_at'=>$s->updated_at]);return Inertia::render('Admin/Stores/Index',['stores'=>$stores]);}
 public function show(Store $store):Response{$store->load(['businessEntity:id,legal_name,trading_name','statusHistories.actor:id,name,email']);return Inertia::render('Admin/Stores/Review',['store'=>$store]);}
 public function start(Request $r,Store $store,ChangeStoreStatus $c):RedirectResponse{abort_unless($store->status===Store::STATUS_PENDING,422);$c->execute($store,Store::STATUS_UNDER_REVIEW,$r->user());return back()->with('success','Review started. Seller editing is now locked.');}
 public function approve(Request $r,Store $store,ChangeStoreStatus $c):RedirectResponse{abort_unless($store->status===Store::STATUS_UNDER_REVIEW,422);$c->execute($store,Store::STATUS_APPROVED,$r->user(),$r->string('note')->toString()?:null);return back()->with('success','Store approved.');}
 public function needsChanges(Request $r,Store $store,ChangeStoreStatus $c):RedirectResponse{$d=$r->validate(['note'=>'required|string|max:2000']);abort_unless($store->status===Store::STATUS_UNDER_REVIEW,422);$c->execute($store,Store::STATUS_NEEDS_CHANGES,$r->user(),$d['note']);return back()->with('success','Store returned to seller with requested changes.');}
 public function reject(Request $r,Store $store,ChangeStoreStatus $c):RedirectResponse{$d=$r->validate(['note'=>'required|string|max:2000']);abort_unless($store->status===Store::STATUS_UNDER_REVIEW,422);$c->execute($store,Store::STATUS_REJECTED,$r->user(),$d['note']);return back()->with('success','Store rejected.');}
 public function suspend(Request $r,Store $store,ChangeStoreStatus $c):RedirectResponse{$d=$r->validate(['note'=>'required|string|max:2000']);abort_unless($store->status===Store::STATUS_APPROVED,422);$c->execute($store,Store::STATUS_SUSPENDED,$r->user(),$d['note']);return back()->with('success','Store suspended.');}
 public function reactivate(Request $r,Store $store,ChangeStoreStatus $c):RedirectResponse{abort_unless($store->status===Store::STATUS_SUSPENDED,422);$c->execute($store,Store::STATUS_APPROVED,$r->user(),$r->string('note')->toString()?:'Store reactivated.');return back()->with('success','Store reactivated.');}
}
