import { Link, router, usePage } from '@inertiajs/react';
import { Building2, ChevronDown, ExternalLink, LayoutDashboard, LogOut, Menu, Store, UserRound, X } from 'lucide-react';
import { ReactNode, useState } from 'react';

type NavItem={label:string;href:string;icon:typeof LayoutDashboard};
type StoreOption={id:number;name:string;business_name?:string};
type Props={children:ReactNode;area:'seller'|'admin';stores?:StoreOption[];activeStoreId?:number|null};

export default function WorkspaceLayout({children,area,stores=[],activeStoreId=null}:Props){
 const {props,url}=usePage<any>(); const [open,setOpen]=useState(false); const user=props.auth?.user;
 const seller=area==='seller';
 const nav:NavItem[]=seller
  ?[{label:'Dashboard',href:'/seller/dashboard',icon:LayoutDashboard},{label:'Business & Stores',href:'/seller/start',icon:Building2}]
  :[{label:'Dashboard',href:'/admin',icon:LayoutDashboard},{label:'Seller Onboarding',href:'/admin/onboarding',icon:UserRound},{label:'Stores',href:'/admin/stores',icon:Store}];
 const active=(href:string)=>href==='/admin'?url==='/admin':url.startsWith(href);
 const sidebar=<div className="flex h-full flex-col bg-slate-950 text-white"><div className="flex h-16 items-center justify-between border-b border-white/10 px-5"><Link href="/" className="text-lg font-extrabold tracking-tight"><span className="text-brand-primary">Dubai</span> Lanka</Link><button onClick={()=>setOpen(false)} className="cursor-pointer rounded-lg p-2 text-white/70 hover:bg-white/10 lg:hidden" aria-label="Close menu"><X size={20}/></button></div><div className="px-4 py-5"><p className="px-2 text-[11px] font-bold uppercase tracking-[.16em] text-white/45">{seller?'Seller Workspace':'Admin Workspace'}</p><nav className="mt-3 space-y-1">{nav.map(item=>{const Icon=item.icon;return <Link key={item.href} href={item.href} onClick={()=>setOpen(false)} className={`flex min-h-11 cursor-pointer items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-bold transition ${active(item.href)?'bg-brand-secondary text-white':'text-white/75 hover:bg-white/10 hover:text-white'}`}><Icon size={18}/>{item.label}</Link>})}</nav></div><div className="mt-auto border-t border-white/10 p-4"><Link href="/" className="flex min-h-11 cursor-pointer items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold text-white/70 hover:bg-white/10 hover:text-white"><ExternalLink size={17}/>View Dubai Lanka</Link><button onClick={()=>router.post('/logout')} className="mt-1 flex min-h-11 w-full cursor-pointer items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm font-semibold text-white/70 hover:bg-white/10 hover:text-white"><LogOut size={17}/>Logout</button></div></div>;
 return <div className="min-h-screen bg-surface-subtle"><aside className="fixed inset-y-0 left-0 z-40 hidden w-64 lg:block">{sidebar}</aside>{open&&<div className="fixed inset-0 z-50 lg:hidden"><button aria-label="Close menu" onClick={()=>setOpen(false)} className="absolute inset-0 cursor-pointer bg-black/45"/><aside className="relative h-full w-[86%] max-w-72">{sidebar}</aside></div>}<div className="lg:pl-64"><header className="sticky top-0 z-30 border-b border-border bg-surface/95 backdrop-blur"><div className="flex min-h-16 items-center gap-3 px-4 sm:px-6"><button onClick={()=>setOpen(true)} className="cursor-pointer rounded-lg border border-border p-2 text-text-primary lg:hidden" aria-label="Open menu"><Menu size={20}/></button><div className="min-w-0 flex-1">{seller&&stores.length>0?<div className="relative max-w-sm"><label className="block text-[10px] font-bold uppercase tracking-wide text-text-muted">Active Store</label><select value={activeStoreId??''} onChange={e=>router.post('/seller/active-store',{store_id:Number(e.target.value)},{preserveScroll:true})} className="w-full cursor-pointer appearance-none bg-transparent pr-7 text-sm font-bold text-text-primary outline-none">{stores.map(s=><option key={s.id} value={s.id}>{s.name}{s.business_name?` — ${s.business_name}`:''}</option>)}</select><ChevronDown className="pointer-events-none absolute bottom-0.5 right-1 size-4 text-text-muted"/></div>:<div><p className="text-xs font-bold uppercase tracking-wide text-text-muted">{seller?'Seller Workspace':'Admin Workspace'}</p><p className="truncate text-sm font-bold text-text-primary">Dubai Lanka</p></div>}</div><div className="hidden text-right sm:block"><p className="max-w-44 truncate text-sm font-bold text-text-primary">{user?.name??'Account'}</p><p className="max-w-44 truncate text-xs text-text-muted">{user?.email}</p></div><div className="flex size-9 items-center justify-center rounded-full bg-brand-secondary-soft text-brand-secondary"><UserRound size={17}/></div></div></header><main>{children}</main></div></div>;
}
